# Generated by Django 4.0 on 2022-01-04 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('DepartmentApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Faculty_ID', models.IntegerField()),
                ('Faculty_Name', models.CharField(max_length=32)),
                ('Faculty_Salary', models.FloatField()),
                ('department', models.ManyToManyField(to='DepartmentApp.Department')),
            ],
        ),
    ]
