# Generated by Django 4.0 on 2022-01-06 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DepartmentApp', '0001_initial'),
        ('FacultyApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='department',
            field=models.ManyToManyField(related_name='department_fac', to='DepartmentApp.Department'),
        ),
    ]
